# Generated by Django 4.1.6 on 2023-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="my_checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Country", models.CharField(max_length=20)),
                ("fname", models.CharField(max_length=15)),
                ("lname", models.CharField(max_length=15)),
                ("companyname", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=50)),
                ("state_country", models.CharField(max_length=20)),
                ("postal_zip", models.IntegerField(max_length=10)),
                ("email_address", models.EmailField(max_length=254)),
                ("Phone", models.IntegerField()),
                ("order_notes", models.TextField()),
                ("Coupon_Code", models.CharField(max_length=20)),
            ],
        ),
    ]
